Stage 1
dandreyanov/GoMarket pull request #1
Opened 2024-04-17 09:53 UTC by dandreyanov

2024-04-22 15:23 UTC, artemovechkin requested changes

2024-04-22 15:23 UTC, artemovechkin commented on cmd/main.go
> +	db, err := sql.Open("sqlite3", "market.db")
с postgres что-то не так пошло?

2024-04-22 15:23 UTC, artemovechkin commented on cmd/main.go
> +
init db предлагаю вынести в отдельную директорию

2024-04-22 15:23 UTC, artemovechkin commented on cmd/main.go
> +	fmt.Println("Creating database")
предлагаю воспользоваться логгером для детектирования подобных событий

2024-04-22 15:23 UTC, artemovechkin commented on internal/handlers/market.go
> +	row := p.db.QueryRow("SELECT * FROM products WHERE id = $1", id)
при update можно указать returning и получить обновленные данные, не выполняя отдельно еще один запрос в бд

2024-04-22 15:23 UTC, artemovechkin commented on internal/handlers/market.go
> +	_, errDb := p.db.Exec("UPDATE products SET name = $1, description = $2, price = $3, quantity = $4 WHERE id = $5", product.Name, product.Description, product.Price, product.Quantity, id)
можно продолжить с тем же неймингом err, не создавая новую переменную

2024-04-22 15:23 UTC, artemovechkin commented on internal/handlers/market.go
> +}
ответ при успешном выполнении 201

2024-04-27 17:59 UTC, dandreyanov commented on cmd/main.go
> +	db, err := sql.Open("sqlite3", "market.db")
на постгрес перееду чуть позже

2024-04-27 19:32 UTC, merged